### ISSUE TITLE
Fails to build on Mac

### ISSUE THREAD

**Issue by pronebird** [heiher/tun2socks#2]
Getting this nasty error:

```
= note: ld: Undefined symbols:
            _hev_task_execute, referenced from:
                _hev_task_system_run_new_task in libtun2socks-9af5adc122d8da4c.rlib[32](hev-task-system-schedule.o)
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am positive that the original repo builds from Makefile on Mac. The project also builds fine if I pull the git repo but it doesn't build when it's a dependency of other crate..

Also I get a barrage of similar messages:

> warning: tun2socks@0.1.2: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: <REDACTED_PROJECT_DIR>/target/debug/build/tun2socks-7ffa9886bf17f9d6/out/libhev-socks5-tunnel.a(pcapif.o) has no symbols

**Comment by heiher** [comment]
Thanks. Fixed by [0.1.3](https://github.com/heiher/tun2socks/releases/tag/0.1.3)
